### ISSUE TITLE
"Scroll down - follow link - back - don't scroll - follow link" fails to scroll to top

### ISSUE THREAD

**Issue by cachvico** [taion/scroll-behavior#15] opened 2015-11-13 00:18 UTC
In Chrome:

1- scroll down a long page
2- click a link - page 2 will be correctly scrolled to the top
3- click Back
4- click the same or any other link without scrolling
5- observe the new page is not scrolled to the top

If after Step 3, a scroll of any distance is performed, the bug does not occur.

From https://github.com/rackt/react-router/issues/2469#issuecomment-153901129

**Comment by taion** [comment] 2015-11-13 02:00
Thanks for filing this! I don't have anything remotely like a solution right now, but it's good to track this - it's definitely a problem.

**Comment by taion** [comment] 2015-11-13 13:46
What version of Chrome are you on? This might just be fixed on Chrome 46+ now.

**Comment by cachvico** [comment] 2015-11-13 20:46
Negative on 46.0.2490.86 (64-bit) (up-to-date)

**Comment by mull** [comment] 2015-11-16 11:05
I can confirm this happens. On latest Safari and Chome 46 as well. My reproduction steps:

1. Scroll down on a long page
2. pushState (react-router) to the next one
3. window *might* not be scrolled up at this point
4. go back (either through pushState or back button)
5. window might or might not be scrolled up

The behaviour is super weird. I've tried increasing the timeout to 500ms and that seems to solve it. Chrome's manual scrollRestoration seems to be broken given that it's definitely restoring the scroll position. However, it doesn't work with Safari either.

`useScrollToTop` seems to not be working on all pushes/replaces either. After triggering the pop bugs, and then "moving forwards" to previously visited pages (using history.pushState) it seems to be scrolling down to previous positions again.

**Comment by taion** [comment] 2015-11-16 13:44
Well, Safari doesn't support scrollRestoration at all, so nothing I can do there. Definitely weird that Chrome scrolls you up even with scrollRestoration disabled, though.

How many of these bugs were present with RR 0.13? It's possible this one is just unfixable for now.

**Comment by mull** [comment] 2015-11-16 15:39
We used `ignoreScrollBehavior` on the one route this is causing issues on previously. I hadn't heard any complaints on any browser, which is why I assumed it works on Safari. Might be wrong. :-)

We had no issues at all on RR 0.13. It is possible that I'm using it wrong. This bug is on my list of things to look more at. It occurred during a ridiculous big feature called _upgrade to React 0.14 and react-router@1.0.0_ :grin: I'll try and get back to you with more details later on, hopefully even a fix.

**Comment by mmahalwy** [comment] 2016-01-21 21:53
@cachvico any update on this? I am experiencing this too

**Comment by cachvico** [comment] 2016-01-21 23:15
I confess I never actually got scroll-behaviour integrated. I first used a [snippet](https://github.com/rackt/react-router/issues/2144#issuecomment-150939358) of code posted in one of the comments that precursed the creation of this package, and it worked more-or-less. When scroll-behaviour came into existence I tried to integrate it but had problems. I was going to ask for help/docs but ran out of time, so I stuck with the original hack - until a big package update broke the build and I had to look at it again. I again tried to integrate scroll-behavior but still had problems (this is probably just a documentation thing), and in the end I came up with a different (very simple) that seemed to do the job for me.

I was wondering, @taion et. al, what do you think about this approach?

```
import createHistory from 'history/lib/createBrowserHistory'

const history = createHistory();

history.listen(function(loc) {
    // Don't scroll to top if user presses back or on replaceState
    if (loc.action === 'POP' || loc.action === 'REPLACE') {
        return;
    }

    // Allow the client to control scroll-to-top using location.state
    if (loc.state && loc.state.scroll !== undefined && !loc.state.scroll) {
        return;
    }

    // 200ms delay hack (for Firefox?)
    setTimeout(() => {
        window.scrollTo(0, 0);
    }, 200);
});


module.exports = history;
```

It is used like this:


```
var history = require('history');

var C = React.createClass({
    mixins: [ History ],

    buttonClicked: function() {
        // Prevent scroll-to-top in an event handler:
        this.history.replaceState({ scroll: false }, '/');
    },
    render: function() {
        return (
            // Prevent scroll-to-top with a <Link>:
            <Link to='/' state={{ scroll: false }}>
    },
});

// ...
<Router history={history}>
    <Route ...

```

**Comment by cachvico** [comment] 2016-01-21 23:16
n.b. @mmahalwy the 200ms delay hack is the actual workaround for this Issue in question

**Comment by mmahalwy** [comment] 2016-01-21 23:54
Awesome! Thanks for sharing! @cachvico

**Comment by taion** [comment] 2016-01-22 00:20
I'm probably going to rewrite this to leverage `<Router render>` when I get a chance.

**Comment by mmahalwy** [comment] 2016-01-28 23:36
@taion how can i help? I dont have a ton of knowledge of how react-router works but i want to help

**Comment by pc035860** [comment] 2016-03-18 12:52
This is actually a bug in Chromium, Opera also demonstrates the same behavior.
https://bugs.chromium.org/p/chromium/issues/detail?id=533742&q=hotlist%3Ainput-dev&sort=pri%20mstone&colspec=ID%20Pri%20Mstone%20ReleaseBlock%20OS%20Area%20Feature%20Status%20Owner%20Summary

And it's fixed in Chrome 49 released on 2 March. ([commit](https://chromium.googlesource.com/chromium/src/+/91e6e97ccdc0d6cdd4e3543102ccc0f90a6da004))
http://googlechromereleases.blogspot.tw/2016/03/stable-channel-update.html

Opera also get fixed in Opera 36 two days ago
http://www.opera.com/docs/changelogs/unified/3600/

**Comment by taion** [comment] 2016-04-14 02:15
Appears to be fixed now.

**Closed by taion** 2016-04-14 02:15 UTC
